// client: // {fio: "fio", phone: "38 (656) 546-56-54", email: "vale123lov@gmail.com", ig_username: "instagramm",…}
additional_field: "comment-2",
comment: "comment",
email: "vale123lov@gmail.com",
fio: "fio",
ig_username: "instagramm",
phone: "38 (656) 546-56-54",
date_create: "",
// delivery: // {delivery_type: "12", responsible_packer: "1", payment_type: "16", prepay_amount: "123",…}
backward_delivery_summ: "1315.64",
cost: "",
delivery_payers: "Sender",
delivery_payers_redelivery: "Recipient",
delivery_service_type: "1",
delivery_type: "12",
doors_address: "",
doors_city: "",
doors_flat: "",
doors_house: "",
novaposhta_comment: "датали-16 - 1;Одежда-красный-50-52 - 1;comment;датали-16 - 1;Одежда-красный-50-52 - 1;",
payment_status: "1",
payment_type: "16",
prepay_amount: "123",
responsible_packer: "1",
seats_amount: "2",
status: "",
tnn: "",
volume_general: "123",
warehouse_address: "Відділення №3 (до 30 кг): просп. Свободи (ран. 60-річчя Жовтня), 77",
warehouse_city: "Кременчук",
weight: "12",
discount: "",
discount_type: "0",

order_products: [,…],
// 0: {presale_type: "0", product_id: "15", amount: "1", price: "1234.00", supplier: "2", discount: "2",…}
amount:"1",
attribute: [{id: 27}],
discount: "2",
discount_type: "0",
presale_type: "0",
price: "1234.00",
product_id: "15",
supplier: "2",
// 1: {presale_type: "0", product_id: "13", amount: "1", price: "234.00", supplier: "0", discount: "2",…}
amount: "1",
attribute: [{id: 6}, {id: 7}],
0: {id: 6}1: {id: 7},
discount: "2",
discount_type: "0",
presale_type: "0",
price: "234.00",
product_id: "13",
supplier: "0",
responsible: "1",
responsible_group: "0",
status: "4",
store_url: ""