export const dataParse ={
    "orders_status_count":[
    {
    "id":0,
    "name":"Все",
    "style":"#afff",
    "count":185
    },
    {
    "id":"4",
    "style":"#a2c4c9",
    "sort":"1",
    "name":"1Новый",
    "count":"149"
    },
    {
    "id":"119",
    "style":"#00ff00",
    "sort":"2",
    "name":"Старт",
    "count":"6"
    },
    {
    "id":"120",
    "style":"#6aa84f",
    "sort":"3",
    "name":"Тест",
    "count":"1"
    },
    {
    "id":"113",
    "style":"#d0e0e3",
    "sort":"5",
    "name":"tolega",
    "count":"0"
    },
    {
    "id":"111",
    "style":"#9fc5e8",
    "sort":"6",
    "name":"Telega",
    "count":"0"
    },
    {
    "id":"106",
    "style":"#9fc5e8",
    "sort":"12",
    "name":"Morj",
    "count":"0"
    },
    {
    "id":"107",
    "style":"#6fa8dc",
    "sort":"13",
    "name":"Morjik",
    "count":"0"
    },
    {
    "id":"102",
    "style":"#20124d",
    "sort":"15",
    "name":"nТест",
    "count":"0"
    },
    {
    "id":"110",
    "style":"#c27ba0",
    "sort":"15",
    "name":"VIber_2",
    "count":"0"
    },
    {
    "id":"103",
    "style":"#c27ba0",
    "sort":"16",
    "name":"fors",
    "count":"0"
    },
    {
    "id":"122",
    "style":"#ff00ff",
    "sort":"19",
    "name":"Гох",
    "count":"4"
    },
    {
    "id":"5",
    "style":"#9aea68",
    "sort":"20",
    "name":"Принято",
    "count":"7"
    },
    {
    "id":"18",
    "style":"#ead1dc",
    "sort":"30",
    "name":"Недозвон",
    "count":"0"
    },
    {
    "id":"19",
    "style":"#85aff5",
    "sort":"40",
    "name":"Нелид",
    "count":"0"
    },
    {
    "id":"9",
    "style":"#ffa4a4",
    "sort":"40",
    "name":"Отказ",
    "count":"0"
    },
    {
    "id":"20",
    "style":"#b96565",
    "sort":"50",
    "name":"Нет в наличии",
    "count":"1"
    },
    {
    "id":"105",
    "style":"#990000",
    "sort":"55",
    "name":"Not Ok",
    "count":"0"
    },
    {
    "id":"104",
    "style":"#ccc",
    "sort":"67",
    "name":"Short List",
    "count":"0"
    },
    {
    "id":"86",
    "style":"#e8b5ce",
    "sort":"69",
    "name":"Готовится к отправке",
    "count":"4"
    },
    {
    "id":"6",
    "style":"#ffe599",
    "sort":"70",
    "name":"Отправлено",
    "count":"6"
    },
    {
    "id":"87",
    "style":"#b45f06",
    "sort":"80",
    "name":"В отделении",
    "count":"0"
    },
    {
    "id":"23",
    "style":"#b6d7a8",
    "sort":"90",
    "name":"В пути деньги (наложка)",
    "count":"0"
    },
    {
    "id":"98",
    "style":"#a64d79",
    "sort":"95",
    "name":"Уточнить",
    "count":"0"
    },
    {
    "id":"125",
    "style":"#ccc",
    "sort":"98",
    "name":"Test 2",
    "count":"0"
    },
    {
    "id":"124",
    "style":"#cccccc",
    "sort":"99",
    "name":"Test",
    "count":"0"
    },
    {
    "id":"101",
    "style":"#ffd966",
    "sort":"100",
    "name":"Ночник",
    "count":"0"
    },
    {
    "id":"24",
    "style":"#fd776e",
    "sort":"100",
    "name":"Возврат товара (в пути)",
    "count":"6"
    },
    {
    "id":"82",
    "style":"#ff0000",
    "sort":"110",
    "name":"Утилизация",
    "count":"0"
    },
    {
    "id":"7",
    "style":"#00cf15",
    "sort":"120",
    "name":"Завершено",
    "count":"1"
    },
    {
    "id":"8",
    "style":"#ff0000",
    "sort":"130",
    "name":"Возврат",
    "count":"0"
    },
    {
    "id":"32",
    "style":"#ec0c0c",
    "sort":"140",
    "name":"Корзина",
    "count":"2"
    }
    ]
    }