export const translater = {
    "id":"Замовлення",
    "client_id":"377",
    "store_id":"Відповідальний магазин",
    "store_url":"Сайт",
    "script_id":"1",
    "responsible":"Admin",
    "responsible_group":"0",
    "responsible_packer":"0",
    "status":"4",
    "delivery_type":null,
    "delivery_price":"Ціна доставки",
    "payment_type":"Тип оплати",
    "payment_status":"0",
    "prepay_amount":"0.00",
    "payment_received":"0",
    "discount":"0",
    "discount_type":"0",
    "order_return":"0",
    "total":"Ціна",
    "backward_delivery_summ":"0.00",
    "total_weight":"Розрахункова вартість",
    "total_volume_general":"Собівартість",
    "comment":"Коментар",
    "client_comment":"",
    "additional_field":"",
    "utm_source":null,
    "utm_medium":null,
    "utm_term":null,
    "utm_content":null,
    "utm_campaign":null,
    "datetime":"Дата додавання",
    "update_at":"Дата зміни",
    "view_id":"1",
    "new_datetime":"2022-10-14 14:16:00",
    "datetime_sent":"Дата відправлення",
    "DT_RowId":"117680",
    "delivery_type_id":"Пошта",
    "client": "ПІБ клієнта",
    "client_phone":"Телефон",
    "banned_phone":"0",
    "ig_username":"",
    "client_ip":"ІР-адреси",
    "count_calls":null,
    "sms_count":null,
    "packer_name":"Контрагент",
    "group_name":"Група",
    "status_name":"1Новый",
    "status_style":"Статус",
    "products_names":"Найменування",
    "product_amount":"1",
    "system_action":"",
    "storage_income_price_sum":"1.00",
    "payment_name":"Спосіб оплати",
    "j_number":null,
    "justin_account":null,
    "j_ttn_cost":null,
    "j_status":"",
    "j_name":null,
    "ttn":"ТТН",
    "ttn_cost":"0.00",
    "ttn_status":"Статус доставки",
    "ttn_status_code":null,
    "ttn_update_at":null,
    "novaposhta_account":null,
    "counterparty":"",
    "barcode":null,
    "barcode_cost":null,
    "barcode_status":null,
    "ukrposhta_account":null,
    "store_title":null,
    "store_responsible":null,
    "name_store_resp":null,
    "supplier": "Постачальник",
    "client_groups":"Група клієнта",
    "repeat_client":"1",
    "doubl_client":1
    }