export const translater = {
    "id":"Замовлення",
    // "client_id":"377",
    "store_id":"Відповідальний магазин",
    "store_url":"Сайт",
    // "script_id":"1",
    "responsible":"Відповідальний",
    // "responsible_group":"0",
    // "responsible_packer":"0",
    // "status":"Статус",
    "delivery_type": 'Тип доставки',
    "delivery_price":"Ціна доставки",
    "payment_type":"Тип оплати",
    "payment_status":"Оплата",
    "prepay_amount":"Сума передплати",
    "payment_received": "Оплата отримана",
    "discount":"Знижка",
    // "discount_type":"0",
    // "order_return":"0",
    // "total":"Ціна",
    "backward_delivery_summ":"Зворотня ддоставки",
    "total_weight":"Повна Маса",
    // "total_volume_general":"Собівартість",
    "comment":"Коментар",
    "client_comment":"Коментар клієнта",
    "additional_field":"Доп. Коментар",
    "utm_source": 'utm_source',
    "utm_medium":"utm_medium",
    "utm_term":"utm_term",
    "utm_content":"utm_content",
    "utm_campaign":"utm_campaign",
    "datetime":"Дата додавання",
    "update_at":"Дата зміни",
    // "view_id":"1",
    "new_datetime":"Нова дата",
    "datetime_sent":"Дата відправлення",
    // "DT_RowId":"117680",
    "delivery_type_id":"Доставка",
    "client": "ПІБ клієнта",
    "client_phone":"Телефон",
    // "banned_phone":"0",
    "ig_username":"Instagram",
    "client_ip":"ІР-адреса",
    // "count_calls":null,
    // "sms_count":null,
    "packer_name":"Пакувальник",
    "group_name":"Група",
    "status_name":"Статус",
    // "status_style":"Статус",
    "products_names":"Найменування",
    // "product_amount":"1",
    // "system_action":"",
    "storage_income_price_sum": "Ціна",
    // "payment_name":"Спосіб оплати",
    // "j_number":null,
    // "justin_account":null,
    // "j_ttn_cost":null,
    // "j_status":"",
    // "j_name":null,
    "ttn":"ТТН",
    "ttn_cost":"Розрахована вартість",
    "ttn_status":"Статус ТТН",
    // "ttn_status_code":null,
    // "ttn_update_at":null,
    // "novaposhta_account":null,
    // "counterparty":"",
    // "barcode":null,
    // "barcode_cost":null,
    // "barcode_status":null,
    // "ukrposhta_account":null,
    // "store_title":null,
    // "store_responsible":null,
    // "name_store_resp":null,
    "supplier": "Постачальник",
    // "client_groups":"Група клієнта",
    // "repeat_client":"1",
    // "doubl_client":1,
    marketing: 'Маркетинг',

    };

export const messages={
   countOrder: 'Оновлено замовлень:',
    statusPrepay: 'Статус передплати змінено',
    dateUpdate: 'Дату відправки встановлено',
    idSelectedWarn: 'Потрібно вибрати хоч одне замовлення',
    idSelectedOne: 'Потрібно вибрати тільки одне замовлення',
    idSelectedFile: 'Потрібно вибрати файл для відправки',
    orderttnError: 'Помилка в замовлені'
}

export const typeMessage={
    error: "error",
    warn: "warning",
    info: "info",
    success: "success",
}