banned: "0",
client_banned: "0",
client_date_of_creation: "2022-11-15 01:07:59",
client_phone: "384434343434",
comment: null,
date: "2022-11-15 01:07:59",
date_of_creation: "2022-11-15 01:07:59",
deleted: "0",
email: "valewww.newTest5ov@gmail.com",
fio: "Walentyn",
first_name: "",
id: "32",
ig_id: "",
ig_username: "www.newTest5",
ip_address: null,
last_name: "",
middle_name: "",
name: "Walentyn",
phone: "384434343434",
responsible: null,
courier: [],
// delivery: {order_id: "55", tnn: "", ref: "", comment: "www.newTest5www.newTest5", seats_amount: "1",…}
comment: "www.newTest5www.newTest5",
cost: "0.00",
cost_product: "0",
counterparty: "",
creation_type: "0",
datetime: null,
doors_address: "",
doors_city: "",
doors_flat: "",
doors_house: "",
novaposhta_account: "0",
order_id: "55",
payer: "Recipient",
payer_redelivery:"Recipient",
ref: "",
return_at: null,
return_number: null,
return_ref: null,
return_ttn: null,
seats_amount: "1",
service_type: "1",
status: "",
status_code: "0",
tnn: "",
update_at: null,
warehouse_address: "Відділення №2: вул. Академіка Янгеля, 40",
warehouse_city: "Дніпро",
history: [],
justin: [],
// order: {id: "55", client_id: "32", prom_id: null, prom_account_id: null, store_id: null,…}
additional_field: "www.newTest5www.newTest5",
backward_delivery_summ: "234.00",
client_comment: "",
client_id: "32",
comment: "www.newTest5www.newTest5",
datetime: "2022-11-10 01:07:59",
datetime_sent: null,
delivery_price: "0.00",
delivery_type: "12",
discount: "0",
discount_type: "0",
id: "55",
new_datetime: null,
order_return: "0",
payment_received: "0",
payment_status: "0",
payment_type: "15",
prepay_amount: "0.00",
presale_total: null,
prom_account_id: null,
prom_id: null,
responsible: "Admin",
responsible_group: "4",
responsible_id: "1",
responsible_packer: "0",
script_id: "1",
status: "4",
store_id: null,
store_responsible: null,
store_title: null,
store_url: "www.newTest5",
total: "0.00",
total_volume_general: "0.0000",
total_weight: "0.00",
update_at: "2022-11-15 01:07:59",
utm_campaign: "",
utm_content: "",
utm_medium: "",
utm_source: "",
utm_term: "",
view_id: "0",
view_name: null,
products
: 
[]

client: {fio: "www.twsttrend", phone: "38 (930) 202-25-68", email: "vwww.twsttrendov@gmail.com",…}
additional_field: "www.twsttrend"
comment: "www.twsttrend"
email: "vwww.twsttrendov@gmail.com"
fio: "www.twsttrend"
ig_username: "www.twsttrend"
phone: "38 (930) 202-25-68"
date_create: "2022-12-22"

backward_delivery_summ: "23",
cost: "",
delivery_payers: "Recipient",
delivery_payers_redelivery: "Recipient",
delivery_service_type: "1",
delivery_type: "12",
doors_address: "",
doors_city: "",
doors_flat: "",
doors_house: "",
novaposhta_comment: "www.twsttrend23",
payment_status: "1",
payment_type: "16",
prepay_amount: "234",
responsible_packer: "1",
seats_amount: "23",
status: "",
tnn: "",
volume_general: "23",
warehouse_address: "Відділення №2: вул. Карпенка-Карого, 58",
warehouse_city: "Запоріжжя",
weight: "23",
discount: "",
discount_type: "0",
order_products: [],
responsible: "1",
responsible_group: "4",
status: "4",
store_url: "www.twsttrend",
